apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: lia-database-f3
  labels:
    app: lia-database-f3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lia-database-f3
    spec:
      hostAliases:
        - ip: "10.140.2.222" 
          hostnames:
            - "branch.falabella.cl"
        - ip: "10.140.2.221"
          hostnames:
            - "boyer.falabella.cl"
      containers:
      - name: lia-database-f3
        image: txdscexrlogliauat.azurecr.io/lia_f3_database:#{Build.BuildId}#
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1.5Gi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: lia-secrets