apiVersion: v1
kind: Service
metadata:
  name: lia-database-f3-svc
  namespace: lia
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: lia-database-f3